# Generated by Django 4.2.4 on 2023-12-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código alfanumérico único', max_length=20, null=True, unique=True),
        ),
    ]
