# Generated by Django 4.2.4 on 2023-12-09 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_alter_alumno_codigo_alter_alumno_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='codigo',
        ),
    ]
