# Generated by Django 4.2.4 on 2023-12-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0004_remove_alumno_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='foto_resultado',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
