# Generated by Django 4.2.4 on 2024-01-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0005_alumno_foto_resultado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='email',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='status',
        ),
        migrations.AddField(
            model_name='alumno',
            name='comentarios',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='foto_resultado',
            field=models.ImageField(blank=True, null=True, upload_to='results/'),
        ),
    ]
