# Generated by Django 4.2.4 on 2024-01-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0006_rename_email_alumno_fecha_remove_alumno_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='fecha',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='alumno',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
