# Generated by Django 4.2.4 on 2024-01-23 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0007_rename_fecha_alumno_email_remove_alumno_comentarios_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='status',
            new_name='fecha',
        ),
    ]
